name: Sync Latest Release and Build

on:
  schedule:
    - cron: '0 3 * * *' # Täglich um 03:00 Uhr
  workflow_dispatch: # Manueller Start möglich

jobs:
  sync-and-build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Fork
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Wichtig, um alle Tags zu erhalten

      - name: Get latest release tag from Upstream
        id: get_tag
        run: |
          # Holt den Namen des neuesten Release-Tags vom Original-Repo
          LATEST_TAG=$(curl -s api.github.com | jq -r .tag_name)
          echo "tag=$LATEST_TAG" >> $GITHUB_OUTPUT

      - name: Sync and Checkout Tag
        run: |
          git remote add upstream 
